version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - webservice

  webservice:
    build: ./webservice
    image: webservice
    build:
      dockerfile: Dockerfile
      context: ./webservice
    volumes:
      - ./webservice:/app

